require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quirks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Quirk. As you add validations to Quirk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Quirk.create! valid_attributes
      get quirks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quirk = Quirk.create! valid_attributes
      get quirk_url(quirk)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quirk_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      quirk = Quirk.create! valid_attributes
      get edit_quirk_url(quirk)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Quirk" do
        expect {
          post quirks_url, params: { quirk: valid_attributes }
        }.to change(Quirk, :count).by(1)
      end

      it "redirects to the created quirk" do
        post quirks_url, params: { quirk: valid_attributes }
        expect(response).to redirect_to(quirk_url(Quirk.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Quirk" do
        expect {
          post quirks_url, params: { quirk: invalid_attributes }
        }.to change(Quirk, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post quirks_url, params: { quirk: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quirk" do
        quirk = Quirk.create! valid_attributes
        patch quirk_url(quirk), params: { quirk: new_attributes }
        quirk.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quirk" do
        quirk = Quirk.create! valid_attributes
        patch quirk_url(quirk), params: { quirk: new_attributes }
        quirk.reload
        expect(response).to redirect_to(quirk_url(quirk))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        quirk = Quirk.create! valid_attributes
        patch quirk_url(quirk), params: { quirk: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quirk" do
      quirk = Quirk.create! valid_attributes
      expect {
        delete quirk_url(quirk)
      }.to change(Quirk, :count).by(-1)
    end

    it "redirects to the quirks list" do
      quirk = Quirk.create! valid_attributes
      delete quirk_url(quirk)
      expect(response).to redirect_to(quirks_url)
    end
  end
end
