require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/twitadvices", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Twitadvice. As you add validations to Twitadvice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Twitadvice.create! valid_attributes
      get twitadvices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      twitadvice = Twitadvice.create! valid_attributes
      get twitadvice_url(twitadvice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_twitadvice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      twitadvice = Twitadvice.create! valid_attributes
      get edit_twitadvice_url(twitadvice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Twitadvice" do
        expect {
          post twitadvices_url, params: { twitadvice: valid_attributes }
        }.to change(Twitadvice, :count).by(1)
      end

      it "redirects to the created twitadvice" do
        post twitadvices_url, params: { twitadvice: valid_attributes }
        expect(response).to redirect_to(twitadvice_url(Twitadvice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Twitadvice" do
        expect {
          post twitadvices_url, params: { twitadvice: invalid_attributes }
        }.to change(Twitadvice, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post twitadvices_url, params: { twitadvice: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested twitadvice" do
        twitadvice = Twitadvice.create! valid_attributes
        patch twitadvice_url(twitadvice), params: { twitadvice: new_attributes }
        twitadvice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the twitadvice" do
        twitadvice = Twitadvice.create! valid_attributes
        patch twitadvice_url(twitadvice), params: { twitadvice: new_attributes }
        twitadvice.reload
        expect(response).to redirect_to(twitadvice_url(twitadvice))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        twitadvice = Twitadvice.create! valid_attributes
        patch twitadvice_url(twitadvice), params: { twitadvice: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested twitadvice" do
      twitadvice = Twitadvice.create! valid_attributes
      expect {
        delete twitadvice_url(twitadvice)
      }.to change(Twitadvice, :count).by(-1)
    end

    it "redirects to the twitadvices list" do
      twitadvice = Twitadvice.create! valid_attributes
      delete twitadvice_url(twitadvice)
      expect(response).to redirect_to(twitadvices_url)
    end
  end
end
